EFUPRODT ; extended efuzy/efuzy-main production regression runner
 ;
 D ^EFUTESTS
 D ^EFUZYTESTS
 I $T(START^EFUZYFSPT)'="" D START^EFUZYFSPT
 I $T(START^EFUWFHISTPT)'="" D START^EFUWFHISTPT
 I $T(START^EFUZYJOBPT2)'="" D START^EFUZYJOBPT2
 I $T(START^EFUZYROUTEPT)'="" D START^EFUZYROUTEPT
 I $T(START^EFUZYUIPT2)'="" D START^EFUZYUIPT2
 I $T(START^EFU837CSVXPT)'="" D START^EFU837CSVXPT
 Q
 ;
