EFUPRODT ; extended efuzy/efuzy-main production regression runner
	;
	D ^EFUTESTS
	D ^EFUZYTESTS
	I $T(START^EFUZYFSPT)'="" D START^EFUZYFSPT
	I $T(START^EFUWFHISTPT)'="" D START^EFUWFHISTPT
	I $T(START^EFUZYJOBPT2)'="" D START^EFUZYJOBPT2
	I $T(START^EFUZYROUTEPT)'="" D START^EFUZYROUTEPT
	I $T(START^EFUZYUIPT2)'="" D START^EFUZYUIPT2
	I $T(START^EFU837CSVXPT)'="" D START^EFU837CSVXPT
	I $T(START^EFUZYCFGPT2)'="" D START^EFUZYCFGPT2
	I $T(START^EFUZYROUTEPT2)'="" D START^EFUZYROUTEPT2
	I $T(START^EFU837CSVPT2)'="" D START^EFU837CSVPT2
	I $T(START^EFUZYJOBPT3)'="" D START^EFUZYJOBPT3
	I $T(START^EFUZYUIPT3)'="" D START^EFUZYUIPT3
	Q
	;
	;