EFUZYTESTS ; efuzy test suite runner
	;
	D START^EFUZYCFGT w 1
	D START^EFUZYCFGPT w 2
	D START^EFUZYJOBT  w 3
	D START^EFUZYFST w 4
	D START^EFUWFHISTT w 5
	D START^EFU837MAPT w 6
	D START^EFU837CSVT w 7
	D START^EFU837CSVPT w 8
	D START^EFU837PT w 9
	D START^EFUWFRUNT w 10
	D START^EFUX12JOBT w 11
	D START^EFUX12JOBPT w 12
	D START^EFUX12WEBT w 13
	D START^EFUX12WEBPT w 14
	D START^EFUZYT w 15
	Q
	;
	;
	;