EFUZYTESTS ; efuzy test suite runner
	;
	D START^EFUZYCFGT
	D START^EFUZYJOBT
	D START^EFUZYFST
	D START^EFUWFHISTT
	D START^EFU837MAPT
	D START^EFU837CSVT
	D START^EFU837PT
	D START^EFUWFRUNT
	D START^EFUZYT
	D START^EFUZYBOOTT
	D START^EFUZYHEALT
	D START^EFUZYLICT
	D START^EFUZYRETT
	D START^EFUZYSTARTT
	I $T(START^EFUZYRELT)'="" D START^EFUZYRELT
	I $T(START^EFUZYDLVT)'="" D START^EFUZYDLVT
	I $T(START^EFUZYCFGPT)'="" D START^EFUZYCFGPT
	I $T(START^EFU837CSVPT)'="" D START^EFU837CSVPT
	I $T(START^EFUX12JOBPT)'="" D START^EFUX12JOBPT
	I $T(START^EFUX12WEBPT)'="" D START^EFUX12WEBPT
	I $T(START^EFUZYUIPT)'="" D START^EFUZYUIPT
	I $T(START^EFUZYFSPT)'="" D START^EFUZYFSPT
	I $T(START^EFUWFHISTPT)'="" D START^EFUWFHISTPT
	I $T(START^EFUZYJOBPT2)'="" D START^EFUZYJOBPT2
	I $T(START^EFUZYROUTEPT)'="" D START^EFUZYROUTEPT
	I $T(START^EFUZYUIPT2)'="" D START^EFUZYUIPT2
	I $T(START^EFU837CSVXPT)'="" D START^EFU837CSVXPT
	I $T(START^EFUZYCFGPT2)'="" D START^EFUZYCFGPT2
	I $T(START^EFUZYROUTEPT2)'="" D START^EFUZYROUTEPT2
	I $T(START^EFU837CSVPT2)'="" D START^EFU837CSVPT2
	I $T(START^EFUZYJOBPT3)'="" D START^EFUZYJOBPT3
	I $T(START^EFUZYUIPT3)'="" D START^EFUZYUIPT3
	I $T(START^EFUZYUIPT4)'="" D START^EFUZYUIPT4
	I $T(START^FUZTESTS)'="" D START^FUZTESTS
	Q
	;
