EFUZYTESTS ; efuzy test suite runner
 D START^EFUZYCFGT
 D START^EFUZYJOBT
 D START^EFUZYFST
 D START^EFUWFHISTT
 D START^EFU837MAPT
 D START^EFU837CSVT
 D START^EFU837PT
 D START^EFUWFRUNT
 D START^EFUZYT
 D START^EFUZYCFGPT
 D START^EFU837CSVPT
 D START^EFUZYUIPT
 Q
 ;
